export enum ModalNames {
  SignIn = 'SignIn',
  SignUp = 'SignUp',
  AddProject = 'AddProject',
  ProjectMenu = 'ProjectMenu',
  ConfirmCode = 'ConfirmCode',
  UpdateProject = 'UpdateProject',
  DeleteProject = 'DeleteProject',
  ResetPassword = 'ResetPassword',
  AddSchemaBulb = 'AddSchemaBulb',
  ForgotPassword = 'ForgotPassword',
  AddSchemaInput = 'AddSchemaInput',
  SchemaBulbMenu = 'SchemaBulbMenu',
  AddControlGauge = 'AddControlGauge',
  SchemaInputMenu = 'SchemaInputMenu',
  AddProjectScreen = 'AddProjectScreen',
  AddControlSwitch = 'AddControlSwitch',
  ControlGaugeMenu = 'ControlGaugeMenu',
  ProjectScreenMenu = 'ProjectScreenMenu',
  ControlSwitchMenu = 'ControlSwitchMenu',
  UpdateControlGauge = 'UpdateControlGauge',
  DeleteControlGauge = 'DeleteControlGauge',
  UpdateProjectScreen = 'UpdateProjectScreen',
  UpdateControlSwitch = 'UpdateControlSwitch',
  DeleteProjectScreen = 'DeleteProjectScreen',
  DeleteControlSwitch = 'DeleteControlSwitch'
}
